"""POSB Silent Accounts — monthly stock-snapshot feed for the BO Lookup
POSB tab's "Silent Accounts & Revival" section (CLAUDE_CODE_PROMPT_BO_Lookup_
Silent.md). Unlike every other section here, an upload isn't month-range
activity to sum — it's a full snapshot of ~10,600 offices as of one point
in time (meta.as_of_month), and offices missing from a given month's
upload simply keep whatever their last known snapshot said (see
merge_cumulative). Matched into BO_LOOKUP by BO Code/SOL ID first (this
file's own primary key), falling back to Office ID — done at assemble
time in pipeline/derive/subdiv_bolookup.py, since that's where BO_LOOKUP's
oid keys and code fields both already exist.

The file's shape (a `meta` key/value sheet plus a `data` sheet, with an
embedded schema_version and checksum) is deliberately self-describing
because Google Forms renames uploads on the way in — nothing here trusts
the filename, only the workbook's own contents.
"""
import hashlib
import openpyxl
import pandas as pd

from pipeline.validate import ValidationError

SHEET_META = "meta"
SHEET_DATA = "data"
SECTION = "posb_silent"

NUMERIC_INT_FIELDS = ["silent_accounts", "sbbas_silent", "sbgen_silent",
                       "live_accounts", "live_sb", "fy_revival_approx"]


def _read_meta(wb) -> dict:
    ws = wb[SHEET_META]
    out = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or row[0] is None:
            continue
        out[str(row[0]).strip()] = row[1]
    return out


def _header_map(ws) -> dict:
    header = next(ws.iter_rows(min_row=1, max_row=1, values_only=True))
    return {str(h).strip(): i for i, h in enumerate(header) if h is not None}


def _data_checksum16(wb) -> str:
    """Must match however the upstream generator computed data_sha256_16:
    the data sheet's raw cell values (native types, no pandas re-inference —
    read_excel's own dtype guessing mangles the numeric-looking office_id
    strings) loaded into a DataFrame and serialized with to_csv(index=False).

    lineterminator is pinned to '\\r\\n' rather than left at pandas' default,
    which follows the running OS (\\r\\n on Windows, \\n on Linux) — the
    upstream generator runs on Windows, so leaving it unpinned made this
    checksum unreproducible on GitHub Actions' Linux runners: every upload
    validated fine locally and failed in CI with an identical file."""
    ws = wb[SHEET_DATA]
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return ""
    header, data_rows = rows[0], rows[1:]
    df = pd.DataFrame(data_rows, columns=header)
    csv_text = df.to_csv(index=False, lineterminator="\r\n")
    return hashlib.sha256(csv_text.encode("utf-8")).hexdigest()[:16]


def _actual_row_count(ws) -> int:
    return sum(1 for r in ws.iter_rows(min_row=2, values_only=True) if any(c is not None for c in r))


def validate(section_cfg: dict, path, month_iso: str, current_as_of: str | None = None) -> list[ValidationError]:
    """current_as_of: the as_of_month already in production for this
    dataset (None if this is the first-ever upload) — passed in by
    build_dataset.run_posb_silent(), which is the only caller; not part of
    the generic run() path every other section uses, since this is the one
    section whose "is this upload allowed" check depends on more than just
    this file's own headers."""
    label = "BO Lookup Silent Accounts file"
    try:
        wb = openpyxl.load_workbook(path, data_only=True)
    except Exception as e:
        return [ValidationError(SECTION, f"{label}: could not open the file — is it a valid Excel (.xlsx) file? ({e})")]

    missing_sheets = [s for s in (SHEET_META, SHEET_DATA) if s not in wb.sheetnames]
    if missing_sheets:
        return [ValidationError(SECTION,
            f"{label}: expected sheets '{SHEET_META}' and '{SHEET_DATA}' — missing {missing_sheets}. "
            f"Found sheets: {wb.sheetnames}. This doesn't look like a BO Lookup Silent Accounts upload.")]

    meta = _read_meta(wb)

    schema_version = str(meta.get("schema_version", "")).strip()
    if schema_version != str(section_cfg.get("schema_version", "1")):
        try:
            is_newer = float(schema_version) > float(section_cfg.get("schema_version", "1"))
        except (TypeError, ValueError):
            is_newer = False
        detail = ("unsupported schema — this file was generated by a newer format than this "
                   "pipeline understands; the pipeline needs an update before it can process it"
                   if is_newer else "missing or unrecognized")
        return [ValidationError(SECTION, f"{label}: {detail} schema_version {schema_version!r} (expected '1').")]

    ws_data = wb[SHEET_DATA]
    header = _header_map(ws_data)
    missing_cols = [c for c in section_cfg["required_data_columns"] if c not in header]
    if missing_cols:
        return [ValidationError(SECTION,
            f"{label}, sheet '{SHEET_DATA}': missing expected column(s) {missing_cols}. "
            f"Please use the template and don't rename or remove columns.")]

    errors = []

    as_of_month = str(meta.get("as_of_month", "")).strip()
    if not as_of_month:
        errors.append(ValidationError(SECTION, f"{label}: meta sheet is missing as_of_month."))

    actual_count = _actual_row_count(ws_data)
    declared_count_raw = meta.get("row_count")
    try:
        declared_count = int(declared_count_raw)
    except (TypeError, ValueError):
        declared_count = None
    if declared_count is None:
        errors.append(ValidationError(SECTION, f"{label}: meta sheet is missing a numeric row_count."))
    elif declared_count != actual_count:
        errors.append(ValidationError(SECTION,
            f"{label}: meta says row_count={declared_count} but the '{SHEET_DATA}' sheet actually has "
            f"{actual_count} data rows — the file looks truncated or hand-edited."))

    declared_checksum = str(meta.get("data_sha256_16", "")).strip()
    if not declared_checksum:
        errors.append(ValidationError(SECTION, f"{label}: meta sheet is missing data_sha256_16."))
    else:
        actual_checksum = _data_checksum16(wb)
        if declared_checksum != actual_checksum:
            errors.append(ValidationError(SECTION,
                f"{label}: checksum mismatch (meta says {declared_checksum}, recomputed {actual_checksum}) — "
                f"the '{SHEET_DATA}' sheet looks truncated or hand-edited since it was generated."))

    if errors:
        return errors  # a corrupt file's as_of_month isn't trustworthy enough to gate on yet

    if as_of_month != month_iso:
        errors.append(ValidationError(SECTION,
            f"{label}: meta says as_of_month={as_of_month!r} but you declared {month_iso!r} in the Form — "
            f"please upload the Silent Accounts file for the month you selected."))

    if not errors and current_as_of is not None and as_of_month <= current_as_of:
        errors.append(ValidationError(SECTION,
            f"{label}: as_of_month {as_of_month!r} is not newer than {current_as_of!r} already in "
            f"production for this dataset — looks like a duplicate or stale re-upload. If this file "
            f"is genuinely a correction, an admin can approve it manually from staging."))

    return errors


def extract(section_cfg: dict, path, month_iso: str) -> dict:
    wb = openpyxl.load_workbook(path, data_only=True)
    meta = _read_meta(wb)
    as_of = str(meta["as_of_month"]).strip()
    fy_months = str(meta.get("months_covered", "")).strip()

    ws = wb[SHEET_DATA]
    idx = _header_map(ws)

    rows = {}
    for r in ws.iter_rows(min_row=2, values_only=True):
        if all(c is None for c in r):
            continue
        code = r[idx["code"]]
        office_id = r[idx["office_id"]]
        if not code and not office_id:
            continue
        key = str(code) if code else f"OID_{office_id}"

        def val(name):
            return r[idx[name]]

        rec = {
            "office_id": str(int(office_id)) if isinstance(office_id, float) else (str(office_id) if office_id is not None else None),
            "office_name": val("office_name"),
            "office_type": val("office_type"),
            "so_name": val("so_name"),
            "sub_division": val("sub_division"),
            "division": val("division"),
            "region": val("region"),
            "silent_ratio_pct": round(float(val("silent_ratio_pct") or 0), 2),
            "revival_basis": val("revival_basis"),
            "as_of": as_of,
            "fy_months": fy_months,
        }
        for f in NUMERIC_INT_FIELDS:
            rec[f] = int(val(f) or 0)
        rows[key] = rec

    return {"as_of": as_of, "fy_months": fy_months, "rows": rows}


def merge_cumulative(new_slice: dict, prev_cumulative: dict | None) -> dict:
    """Snapshot-merge, not a sum: this month's rows overwrite/extend
    whatever was already known; a code absent from this upload keeps its
    previously recorded block untouched (with its own stale `as_of`) —
    that's the point of _meta.as_of tracking the *upload's* as_of
    separately from each row's own, per CLAUDE_CODE_PROMPT_BO_Lookup_Silent.md
    step 4."""
    prev_rows = (prev_cumulative or {}).get("rows", {})
    rows = dict(prev_rows)
    rows.update(new_slice["rows"])
    return {
        "_meta": {"as_of": new_slice["as_of"], "fy_months": new_slice["fy_months"]},
        "rows": rows,
    }


def row_count(data: dict) -> int:
    return len(data.get("rows", {})) if data else 0


def diff_summary(new_slice: dict, prev_cumulative: dict | None) -> dict:
    """Used by build_dataset.py's --check-only dry run to print what would
    change without writing anything."""
    prev_rows = (prev_cumulative or {}).get("rows", {})
    new_rows = new_slice["rows"]
    added = [k for k in new_rows if k not in prev_rows]
    changed = [k for k in new_rows if k in prev_rows and prev_rows[k] != new_rows[k]]
    unchanged = [k for k in new_rows if k in prev_rows and prev_rows[k] == new_rows[k]]
    carried_forward = [k for k in prev_rows if k not in new_rows]
    return {
        "added": len(added), "changed": len(changed),
        "unchanged": len(unchanged), "carried_forward": len(carried_forward),
        "sample_changed": changed[:5], "sample_added": added[:5],
    }
